name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pull_request_title:
    name: Lint pull request title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore
            feat
            fix