name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.6.2

      - name: Setup Go
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Setup Git user
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create new tag
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          next_version=${{ steps.get_next_version.outputs.version }}
          
          git tag $next_version
          git push origin $next_version

      - name: Build for platforms
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: make build-all

      - name: Release binaries
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          tag: ${{ steps.get_next_version.outputs.version }}